export const currencies = [
  {"cc":"AED","emoji":"🇦🇪","symbol":"\u062f.\u0625;","name":"UAE dirham"},
  {"cc":"AFN","emoji":"🇦🇫","symbol":"Afs","name":"Afghan afghani"},
  {"cc":"ALL","emoji":"🇦🇱","symbol":"L","name":"Albanian lek"},
  {"cc":"AMD","emoji":"🇦🇲","symbol":"AMD","name":"Armenian dram"},
  {"cc":"ANG","emoji":"🇨🇼","symbol":"NA\u0192","name":"Netherlands Antillean gulden"},
  {"cc":"AOA","emoji":"🇦🇴","symbol":"Kz","name":"Angolan kwanza"},
  {"cc":"ARS","emoji":"🇦🇷","symbol":"$","name":"Argentine peso"},
  {"cc":"AUD","emoji":"🇦🇺","symbol":"$","name":"Australian dollar"},
  {"cc":"AWG","emoji":"🇦🇼","symbol":"\u0192","name":"Aruban florin"},
  {"cc":"AZN","emoji":"🇦🇿","symbol":"AZN","name":"Azerbaijani manat"},
  {"cc":"BAM","emoji":"🇧🇦","symbol":"KM","name":"Bosnia and Herzegovina konvertibilna marka"},
  {"cc":"BBD","emoji":"🇧🇧","symbol":"Bds$","name":"Barbadian dollar"},
  {"cc":"BDT","emoji":"🇧🇩","symbol":"\u09f3","name":"Bangladeshi taka"},
  {"cc":"BGN","emoji":"🇧🇬","symbol":"BGN","name":"Bulgarian lev"},
  {"cc":"BHD","emoji":"🇧🇭","symbol":".\u062f.\u0628","name":"Bahraini dinar"},
  {"cc":"BIF","emoji":"🇧🇮","symbol":"FBu","name":"Burundi franc"},
  {"cc":"BMD","emoji":"🇧🇲","symbol":"BD$","name":"Bermudian dollar"},
  {"cc":"BND","emoji":"🇧🇳","symbol":"B$","name":"Brunei dollar"},
  {"cc":"BOB","emoji":"🇧🇴","symbol":"Bs.","name":"Bolivian boliviano"},
  {"cc":"BRL","emoji":"🇧🇷","symbol":"R$","name":"Brazilian real"},
  {"cc":"BSD","emoji":"🇧🇸","symbol":"B$","name":"Bahamian dollar"},
  {"cc":"BTN","emoji":"🇧🇹","symbol":"Nu.","name":"Bhutanese ngultrum"},
  {"cc":"BWP","emoji":"🇧🇼","symbol":"P","name":"Botswana pula"},
  {"cc":"BYR","emoji":"🇧🇾","symbol":"Br","name":"Belarusian ruble"},
  {"cc":"BZD","emoji":"🇧🇿","symbol":"BZ$","name":"Belize dollar"},
  {"cc":"CAD","emoji":"🇨🇦","symbol":"$","name":"Canadian dollar"},
  {"cc":"CDF","emoji":"🇨🇩","symbol":"F","name":"Congolese franc"},
  {"cc":"CHF","emoji":"🇨🇭","symbol":"Fr.","name":"Swiss franc"},
  {"cc":"CLP","emoji":"🇨🇱","symbol":"$","name":"Chilean peso"},
  {"cc":"CNY","emoji":"🇨🇳","symbol":"\u00a5","name":"Chinese/Yuan renminbi"},
  {"cc":"COP","emoji":"🇨🇴","symbol":"Col$","name":"Colombian peso"},
  {"cc":"CRC","emoji":"🇨🇷","symbol":"\u20a1","name":"Costa Rican colon"},
  {"cc":"CUC","emoji":"🇨🇺","symbol":"$","name":"Cuban peso"},
  {"cc":"CVE","emoji":"🇨🇻","symbol":"Esc","name":"Cape Verdean escudo"},
  {"cc":"CZK","emoji":"🇨🇿","symbol":"K\u010d","name":"Czech koruna"},
  {"cc":"DJF","emoji":"🇩🇯","symbol":"Fdj","name":"Djiboutian franc"},
  {"cc":"DKK","emoji":"🇩🇰","symbol":"Kr","name":"Danish krone"},
  {"cc":"DOP","emoji":"🇩🇴","symbol":"RD$","name":"Dominican peso"},
  {"cc":"DZD","emoji":"🇩🇿","symbol":"\u062f.\u062c","name":"Algerian dinar"},
  {"cc":"EEK","emoji":"🇪🇪","symbol":"KR","name":"Estonian kroon"},
  {"cc":"EGP","emoji":"🇪🇬","symbol":"\u00a3","name":"Egyptian pound"},
  {"cc":"ERN","emoji":"🇪🇷","symbol":"Nfa","name":"Eritrean nakfa"},
  {"cc":"ETB","emoji":"🇪🇹","symbol":"Br","name":"Ethiopian birr"},
  {"cc":"EUR","emoji":"🇪🇺","symbol":"\u20ac","name":"European Euro"},
  {"cc":"FJD","emoji":"🇫🇯","symbol":"FJ$","name":"Fijian dollar"},
  {"cc":"FKP","emoji":"🇫🇰","symbol":"\u00a3","name":"Falkland Islands pound"},
  {"cc":"GBP","emoji":"🇬🇧","symbol":"\u00a3","name":"British pound"},
  {"cc":"GEL","emoji":"🇬🇪","symbol":"GEL","name":"Georgian lari"},
  {"cc":"GHS","emoji":"🇬🇭","symbol":"GH\u20b5","name":"Ghanaian cedi"},
  {"cc":"GIP","emoji":"🇬🇮","symbol":"\u00a3","name":"Gibraltar pound"},
  {"cc":"GMD","emoji":"🇬🇲","symbol":"D","name":"Gambian dalasi"},
  {"cc":"GNF","emoji":"🇬🇳","symbol":"FG","name":"Guinean franc"},
  {"cc":"GQE","emoji":"🇬🇶","symbol":"CFA","name":"Central African CFA franc"},
  {"cc":"GTQ","emoji":"🇬🇹","symbol":"Q","name":"Guatemalan quetzal"},
  {"cc":"GYD","emoji":"🇬🇾","symbol":"GY$","name":"Guyanese dollar"},
  {"cc":"HKD","emoji":"🇭🇰","symbol":"HK$","name":"Hong Kong dollar"},
  {"cc":"HNL","emoji":"🇭🇳","symbol":"L","name":"Honduran lempira"},
  {"cc":"HRK","emoji":"🇭🇷","symbol":"kn","name":"Croatian kuna"},
  {"cc":"HTG","emoji":"🇭🇹","symbol":"G","name":"Haitian gourde"},
  {"cc":"HUF","emoji":"🇭🇺","symbol":"Ft","name":"Hungarian forint"},
  {"cc":"IDR","emoji":"🇮🇩","symbol":"Rp","name":"Indonesian rupiah"},
  {"cc":"ILS","emoji":"🇮🇱","symbol":"\u20aa","name":"Israeli new sheqel"},
  {"cc":"INR","emoji":"🇮🇳","symbol":"\u20B9","name":"Indian rupee"},
  {"cc":"IQD","emoji":"🇮🇶","symbol":"\u062f.\u0639","name":"Iraqi dinar"},
  {"cc":"IRR","emoji":"🇮🇷","symbol":"IRR","name":"Iranian rial"},
  {"cc":"ISK","emoji":"🇮🇸","symbol":"kr","name":"Icelandic kr\u00f3na"},
  {"cc":"JMD","emoji":"🇯🇲","symbol":"J$","name":"Jamaican dollar"},
  {"cc":"JOD","emoji":"🇯🇴","symbol":"JOD","name":"Jordanian dinar"},
  {"cc":"JPY","emoji":"🇯🇵","symbol":"\u00a5","name":"Japanese yen"},
  {"cc":"KES","emoji":"🇰🇪","symbol":"KSh","name":"Kenyan shilling"},
  {"cc":"KGS","emoji":"🇰🇬","symbol":"\u0441\u043e\u043c","name":"Kyrgyzstani som"},
  {"cc":"KHR","emoji":"🇰🇭","symbol":"\u17db","name":"Cambodian riel"},
  {"cc":"KMF","emoji":"🇰🇲","symbol":"KMF","name":"Comorian franc"},
  {"cc":"KPW","emoji":"🇰🇵","symbol":"W","name":"North Korean won"},
  {"cc":"KRW","emoji":"🇰🇷","symbol":"W","name":"South Korean won"},
  {"cc":"KWD","emoji":"🇰🇼","symbol":"KWD","name":"Kuwaiti dinar"},
  {"cc":"KYD","emoji":"🇰🇾","symbol":"KY$","name":"Cayman Islands dollar"},
  {"cc":"KZT","emoji":"🇰🇿","symbol":"T","name":"Kazakhstani tenge"},
  {"cc":"LAK","emoji":"🇱🇦","symbol":"KN","name":"Lao kip"},
  {"cc":"LBP","emoji":"🇱🇧","symbol":"\u00a3","name":"Lebanese lira"},
  {"cc":"LKR","emoji":"🇱🇰","symbol":"Rs","name":"Sri Lankan rupee"},
  {"cc":"LRD","emoji":"🇱🇷","symbol":"L$","name":"Liberian dollar"},
  {"cc":"LSL","emoji":"🇱🇸","symbol":"M","name":"Lesotho loti"},
  {"cc":"LTL","emoji":"🇱🇹","symbol":"Lt","name":"Lithuanian litas"},
  {"cc":"LVL","emoji":"🇱🇻","symbol":"Ls","name":"Latvian lats"},
  {"cc":"LYD","emoji":"🇱🇾","symbol":"LD","name":"Libyan dinar"},
  {"cc":"MAD","emoji":"🇲🇦","symbol":"MAD","name":"Moroccan dirham"},
  {"cc":"MDL","emoji":"🇲🇩","symbol":"MDL","name":"Moldovan leu"},
  {"cc":"MGA","emoji":"🇲🇬","symbol":"FMG","name":"Malagasy ariary"},
  {"cc":"MKD","emoji":"🇲🇰","symbol":"MKD","name":"Macedonian denar"},
  {"cc":"MMK","emoji":"🇲🇲","symbol":"K","name":"Myanma kyat"},
  {"cc":"MNT","emoji":"🇲🇳","symbol":"\u20ae","name":"Mongolian tugrik"},
  {"cc":"MOP","emoji":"🇲🇴","symbol":"P","name":"Macanese pataca"},
  {"cc":"MRO","emoji":"🇲🇷","symbol":"UM","name":"Mauritanian ouguiya"},
  {"cc":"MUR","emoji":"🇲🇺","symbol":"Rs","name":"Mauritian rupee"},
  {"cc":"MVR","emoji":"🇲🇻","symbol":"Rf","name":"Maldivian rufiyaa"},
  {"cc":"MWK","emoji":"🇲🇼","symbol":"MK","name":"Malawian kwacha"},
  {"cc":"MXN","emoji":"🇲🇽","symbol":"$","name":"Mexican peso"},
  {"cc":"MYR","emoji":"🇲🇾","symbol":"RM","name":"Malaysian ringgit"},
  {"cc":"MZM","emoji":"🇲🇿","symbol":"MTn","name":"Mozambican metical"},
  {"cc":"NAD","emoji":"🇳🇦","symbol":"N$","name":"Namibian dollar"},
  {"cc":"NGN","emoji":"🇳🇬","symbol":"\u20a6","name":"Nigerian naira"},
  {"cc":"NIO","emoji":"🇳🇮","symbol":"C$","name":"Nicaraguan c\u00f3rdoba"},
  {"cc":"NOK","emoji":"🇳🇴","symbol":"kr","name":"Norwegian krone"},
  {"cc":"NPR","emoji":"🇳🇵","symbol":"NRs","name":"Nepalese rupee"},
  {"cc":"NZD","emoji":"🇳🇿","symbol":"NZ$","name":"New Zealand dollar"},
  {"cc":"OMR","emoji":"🇴🇲","symbol":"OMR","name":"Omani rial"},
  {"cc":"PAB","emoji":"🇵🇦","symbol":"B./","name":"Panamanian balboa"},
  {"cc":"PEN","emoji":"🇵🇪","symbol":"S/.","name":"Peruvian nuevo sol"},
  {"cc":"PGK","emoji":"🇵🇬","symbol":"K","name":"Papua New Guinean kina"},
  {"cc":"PHP","emoji":"🇵🇭","symbol":"\u20b1","name":"Philippine peso"},
  {"cc":"PKR","emoji":"🇵🇰","symbol":"Rs.","name":"Pakistani rupee"},
  {"cc":"PLN","emoji":"🇵🇱","symbol":"z\u0142","name":"Polish zloty"},
  {"cc":"PYG","emoji":"🇵🇾","symbol":"\u20b2","name":"Paraguayan guarani"},
  {"cc":"QAR","emoji":"🇶🇦","symbol":"QR","name":"Qatari riyal"},
  {"cc":"RON","emoji":"🇷🇴","symbol":"L","name":"Romanian leu"},
  {"cc":"RSD","emoji":"🇷🇸","symbol":"din.","name":"Serbian dinar"},
  {"cc":"RUB","emoji":"🇷🇺","symbol":"R","name":"Russian ruble"},
  {"cc":"SAR","emoji":"🇸🇦","symbol":"SR","name":"Saudi riyal"},
  {"cc":"SBD","emoji":"🇸🇧","symbol":"SI$","name":"Solomon Islands dollar"},
  {"cc":"SCR","emoji":"🇸🇨","symbol":"SR","name":"Seychellois rupee"},
  {"cc":"SDG","emoji":"🇸🇩","symbol":"SDG","name":"Sudanese pound"},
  {"cc":"SEK","emoji":"🇸🇪","symbol":"kr","name":"Swedish krona"},
  {"cc":"SGD","emoji":"🇸🇬","symbol":"S$","name":"Singapore dollar"},
  {"cc":"SHP","emoji":"🇸🇭","symbol":"\u00a3","name":"Saint Helena pound"},
  {"cc":"SLL","emoji":"🇸🇱","symbol":"Le","name":"Sierra Leonean leone"},
  {"cc":"SOS","emoji":"🇸🇴","symbol":"Sh.","name":"Somali shilling"},
  {"cc":"SRD","emoji":"🇸🇷","symbol":"$","name":"Surinamese dollar"},
  {"cc":"SYP","emoji":"🇸🇾","symbol":"LS","name":"Syrian pound"},
  {"cc":"SZL","emoji":"🇸🇿","symbol":"E","name":"Swazi lilangeni"},
  {"cc":"THB","emoji":"🇹🇭","symbol":"\u0e3f","name":"Thai baht"},
  {"cc":"TJS","emoji":"🇹🇯","symbol":"TJS","name":"Tajikistani somoni"},
  {"cc":"TMT","emoji":"🇹🇲","symbol":"m","name":"Turkmen manat"},
  {"cc":"TND","emoji":"🇹🇳","symbol":"DT","name":"Tunisian dinar"},
  {"cc":"TRY","emoji":"🇹🇷","symbol":"TRY","name":"Turkish new lira"},
  {"cc":"TTD","emoji":"🇹🇹","symbol":"TT$","name":"Trinidad and Tobago dollar"},
  {"cc":"TWD","emoji":"🇹🇼","symbol":"NT$","name":"New Taiwan dollar"},
  {"cc":"TZS","emoji":"🇹🇿","symbol":"TZS","name":"Tanzanian shilling"},
  {"cc":"UAH","emoji":"🇺🇦","symbol":"UAH","name":"Ukrainian hryvnia"},
  {"cc":"UGX","emoji":"🇺🇬","symbol":"USh","name":"Ugandan shilling"},
  {"cc":"USD","emoji":"🇺🇸","symbol":"US$","name":"United States dollar"},
  {"cc":"UYU","emoji":"🇺🇾","symbol":"$U","name":"Uruguayan peso"},
  {"cc":"UZS","emoji":"🇺🇿","symbol":"UZS","name":"Uzbekistani som"},
  {"cc":"VEB","emoji":"🇻🇪","symbol":"Bs","name":"Venezuelan bolivar"},
  {"cc":"VND","emoji":"🇻🇳","symbol":"\u20ab","name":"Vietnamese dong"},
  {"cc":"VUV","emoji":"🇻🇺","symbol":"VT","name":"Vanuatu vatu"},
  {"cc":"WST","emoji":"🇼🇸","symbol":"WS$","name":"Samoan tala"},
  {"cc":"XAF","emoji":"🌍","symbol":"CFA","name":"Central African CFA franc"},
  {"cc":"XCD","emoji":"🌎","symbol":"EC$","name":"East Caribbean dollar"},
  {"cc":"XDR","emoji":"🏦","symbol":"SDR","name":"Special Drawing Rights"},
  {"cc":"XOF","emoji":"🌍","symbol":"CFA","name":"West African CFA franc"},
  {"cc":"XPF","emoji":"🇵🇫","symbol":"F","name":"CFP franc"},
  {"cc":"YER","emoji":"🇾🇪","symbol":"YER","name":"Yemeni rial"},
  {"cc":"ZAR","emoji":"🇿🇦","symbol":"R","name":"South African rand"},
  {"cc":"ZMK","emoji":"🇿🇲","symbol":"ZK","name":"Zambian kwacha"},
  {"cc":"ZWR","emoji":"🇿🇼","symbol":"Z$","name":"Zimbabwean dollar"}
]