import React from "react";
import Link from "next/link";
import {
  Table,
  TableBody,
  TableCell,
  TableCaption,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { EllipsisVertical } from "lucide-react";
import { TableFooter } from "@/components/ui/table";
import { TablePagination } from "@/components/TablePagination";
import FollowerColumn from "@/components/dashboard/FollowerColumn";
import { FollowerColumnType } from "@/utils/types/Dashboard";
import { DataTable } from "@/components/data-table";

const page = () => {
  const headers = ["Username", "Followed You Since", "Like", "Comments"];
  const followers: FollowerColumnType[] = [
    {
      id: "1",
      username: "john_doe",
      followed_since: "2023-09-15",
      like: "12",
      comments: "5",
      avatar_url: "https://example.com/avatar1.jpg",
      full_name: "John Doe",
      follower_id: "follower1",
      profile_id: "profile1",
    },
    {
      id: "2",
      username: "jane_smith",
      followed_since: "2024-01-22",
      like: "8",
      comments: "2",
      avatar_url: "https://example.com/avatar2.jpg",
      full_name: "Jane Smith",
      follower_id: "follower2",
      profile_id: "profile2",
    },
    {
      id: "3",
      username: "alex_king",
      followed_since: "2023-12-03",
      like: "15",
      comments: "7",
      avatar_url: "https://example.com/avatar3.jpg",
      full_name: "Alex King",
      follower_id: "follower3",
      profile_id: "profile3",
    },
    {
      id: "4",
      username: "sara_lee",
      followed_since: "2024-03-10",
      like: "5",
      comments: "1",
      avatar_url: "https://example.com/avatar4.jpg",
      full_name: "Sara Lee",
      follower_id: "follower4",
      profile_id: "profile4",
    },
    {
      id: "5",
      username: "mike_jones",
      followed_since: "2023-11-18",
      like: "10",
      comments: "3",
      avatar_url: "https://example.com/avatar5.jpg",
      full_name: "Mike Jones",
      follower_id: "follower5",
      profile_id: "profile5",
    },
    {
      id: "6",
      username: "lisa_brown",
      followed_since: "2024-02-01",
      like: "13",
      comments: "6",
      avatar_url: "https://example.com/avatar6.jpg",
      full_name: "Lisa Brown",
      follower_id: "follower6",
      profile_id: "profile6",
    },
    {
      id: "7",
      username: "david_wilson",
      followed_since: "2023-10-27",
      like: "7",
      comments: "2",
      avatar_url: "https://example.com/avatar7.jpg",
      full_name: "David Wilson",
      follower_id: "follower7",
      profile_id: "profile7",
    },
    {
      id: "8",
      username: "emily_davis",
      followed_since: "2024-03-15",
      like: "11",
      comments: "4",
      avatar_url: "https://example.com/avatar8.jpg",
      full_name: "Emily Davis",
      follower_id: "follower8",
      profile_id: "profile8",
    },
    {
      id: "9",
      username: "kevin_miller",
      followed_since: "2023-09-05",
      like: "9",
      comments: "3",
      avatar_url: "https://example.com/avatar9.jpg",
      full_name: "Kevin Miller",
      follower_id: "follower9",
      profile_id: "profile9",
    },
    {
      id: "10",
      username: "amanda_white",
      followed_since: "2024-01-10",
      like: "6",
      comments: "1",
      avatar_url: "https://example.com/avatar10.jpg",
      full_name: "Amanda White",
      follower_id: "follower10",
      profile_id: "profile10",
    },
    {
      id: "11",
      username: "ryan_harris",
      followed_since: "2023-12-20",
      like: "14",
      comments: "8",
      avatar_url: "https://example.com/avatar11.jpg",
      full_name: "Ryan Harris",
      follower_id: "follower11",
      profile_id: "profile11",
    },
    {
      id: "12",
      username: "megan_clark",
      followed_since: "2024-02-28",
      like: "4",
      comments: "0",
      avatar_url: "https://example.com/avatar12.jpg",
      full_name: "Megan Clark",
      follower_id: "follower12",
      profile_id: "profile12",
    },
    {
      id: "13",
      username: "justin_lewis",
      followed_since: "2023-11-01",
      like: "12",
      comments: "5",
      avatar_url: "https://example.com/avatar13.jpg",
      full_name: "Justin Lewis",
      follower_id: "follower13",
      profile_id: "profile13",
    },
    {
      id: "14",
      username: "nicole_hall",
      followed_since: "2024-03-01",
      like: "8",
      comments: "2",
      avatar_url: "https://example.com/avatar14.jpg",
      full_name: "Nicole Hall",
      follower_id: "follower14",
      profile_id: "profile14",
    },
    {
      id: "15",
      username: "brandon_young",
      followed_since: "2023-10-15",
      like: "15",
      comments: "7",
      avatar_url: "https://example.com/avatar15.jpg",
      full_name: "Brandon Young",
      follower_id: "follower15",
      profile_id: "profile15",
    },
    {
      id: "16",
      username: "heather_allen",
      followed_since: "2024-01-05",
      like: "5",
      comments: "1",
      avatar_url: "https://example.com/avatar16.jpg",
      full_name: "Heather Allen",
      follower_id: "follower16",
      profile_id: "profile16",
    },
    {
      id: "17",
      username: "corey_wright",
      followed_since: "2023-09-25",
      like: "10",
      comments: "3",
      avatar_url: "https://example.com/avatar17.jpg",
      full_name: "Corey Wright",
      follower_id: "follower17",
      profile_id: "profile17",
    },
    {
      id: "18",
      username: "angela_scott",
      followed_since: "2024-02-15",
      like: "13",
      comments: "6",
      avatar_url: "https://example.com/avatar18.jpg",
      full_name: "Angela Scott",
      follower_id: "follower18",
      profile_id: "profile18",
    },
    {
      id: "19",
      username: "todd_green",
      followed_since: "2023-12-10",
      like: "7",
      comments: "2",
      avatar_url: "https://example.com/avatar19.jpg",
      full_name: "Todd Green",
      follower_id: "follower19",
      profile_id: "profile19",
    },
    {
      id: "20",
      username: "samantha_baker",
      followed_since: "2024-03-20",
      like: "11",
      comments: "4",
      avatar_url: "https://example.com/avatar20.jpg",
      full_name: "Samantha Baker",
      follower_id: "follower20",
      profile_id: "profile20",
    },
    {
      id: "21",
      username: "brendan_nelson",
      followed_since: "2023-11-25",
      like: "9",
      comments: "3",
      avatar_url: "https://example.com/avatar21.jpg",
      full_name: "Brendan Nelson",
      follower_id: "follower21",
      profile_id: "profile21",
    },
    {
      id: "22",
      username: "vanessa_carter",
      followed_since: "2024-01-30",
      like: "6",
      comments: "1",
      avatar_url: "https://example.com/avatar22.jpg",
      full_name: "Vanessa Carter",
      follower_id: "follower22",
      profile_id: "profile22",
    },
    {
      id: "23",
      username: "jeremy_perez",
      followed_since: "2023-10-05",
      like: "14",
      comments: "8",
      avatar_url: "https://example.com/avatar23.jpg",
      full_name: "Jeremy Perez",
      follower_id: "follower23",
      profile_id: "profile23",
    },
    {
      id: "24",
      username: "melissa_roberts",
      followed_since: "2024-02-20",
      like: "4",
      comments: "0",
      avatar_url: "https://example.com/avatar24.jpg",
      full_name: "Melissa Roberts",
      follower_id: "follower24",
      profile_id: "profile24",
    },
    {
      id: "25",
      username: "anthony_turner",
      followed_since: "2023-09-30",
      like: "12",
      comments: "5",
      avatar_url: "https://example.com/avatar25.jpg",
      full_name: "Anthony Turner",
      follower_id: "follower25",
      profile_id: "profile25",
    },
    {
      id: "26",
      username: "stephanie_phillips",
      followed_since: "2024-01-15",
      like: "8",
      comments: "2",
      avatar_url: "https://example.com/avatar26.jpg",
      full_name: "Stephanie Phillips",
      follower_id: "follower26",
      profile_id: "profile26",
    },
    {
      id: "27",
      username: "charles_campbell",
      followed_since: "2023-12-05",
      like: "15",
      comments: "7",
      avatar_url: "https://example.com/avatar27.jpg",
      full_name: "Charles Campbell",
      follower_id: "follower27",
      profile_id: "profile27",
    },
    {
      id: "28",
      username: "michelle_parker",
      followed_since: "2024-03-05",
      like: "5",
      comments: "1",
      avatar_url: "https://example.com/avatar28.jpg",
      full_name: "Michelle Parker",
      follower_id: "follower28",
      profile_id: "profile28",
    },
    {
      id: "29",
      username: "joshua_evans",
      followed_since: "2023-11-10",
      like: "10",
      comments: "3",
      avatar_url: "https://example.com/avatar29.jpg",
      full_name: "Joshua Evans",
      follower_id: "follower29",
      profile_id: "profile29",
    },
    {
      id: "30",
      username: "olivia_edwards",
      followed_since: "2024-02-05",
      like: "13",
      comments: "6",
      avatar_url: "https://example.com/avatar30.jpg",
      full_name: "Olivia Edwards",
      follower_id: "follower30",
      profile_id: "profile30",
    },
    {
      id: "31",
      username: "gary_collins",
      followed_since: "2023-10-20",
      like: "7",
      comments: "2",
      avatar_url: "https://example.com/avatar31.jpg",
      full_name: "Gary Collins",
      follower_id: "follower31",
      profile_id: "profile31",
    },
    {
      id: "32",
      username: "natalie_stewart",
      followed_since: "2024-03-25",
      like: "11",
      comments: "4",
      avatar_url: "https://example.com/avatar32.jpg",
      full_name: "Natalie Stewart",
      follower_id: "follower32",
      profile_id: "profile32",
    },
    {
      id: "33",
      username: "christian_flores",
      followed_since: "2023-09-10",
      like: "9",
      comments: "3",
      avatar_url: "https://example.com/avatar33.jpg",
      full_name: "Christian Flores",
      follower_id: "follower33",
      profile_id: "profile33",
    },
  ];
  return (
    <div className="mx-5 md:mx-10">
      <div className="mt-4 text-center md:text-left">
        <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 sm:mb-4">
          Your Followers
        </h2>
        <p className="mb-4 sm:mb-6 text-gray-600 max-w-full text-sm sm:text-base">
          Here's a summary of everyone following you. See when they started, how
          they interact, and connect with your community!
        </p>
      </div>
      <div className="overflow-x-visible w-full px-2 sm:px-4 md:px-0">
        <DataTable<FollowerColumnType, any>
          columns={FollowerColumn}
          data={followers}
        />
      </div>
    </div>
  );
};

export default page;
