CREATE TABLE IF NOT EXISTS meal_plan (
    id BIGINT not null generated by default as identity primary key,
    name TEXT not null,
    timeframe TEXT NOT NULL,
    goal TEXT NOT NULL,
    diet TEXT NOT NULL,
    calories INTEGER NOT NULL CHECK (calories > 0),
    meals_per_day INTEGER NOT NULL CHECK (meals_per_day > 0 AND meals_per_day <= 10),
    shopping_list JSONB,
    notes TEXT,
    pro_tips JSONB,
    author_id UUID NOT NULL REFERENCES profile(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);



ALTER TABLE meal_plan
ADD COLUMN slug TEXT NOT NULL;

-- Indexes for meal_plan
CREATE INDEX IF NOT EXISTS idx_meal_plan_author_id ON meal_plan(author_id);
CREATE INDEX IF NOT EXISTS idx_meal_plan_created_at ON meal_plan(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_meal_plan_slug ON meal_plan(slug);

-- Enable RLS for meal_plan
ALTER TABLE meal_plan ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view meal plans
CREATE POLICY "Meal plans are viewable by everyone"
    ON meal_plan FOR SELECT
    USING (true);

-- Policy: Users can create their own meal plans
CREATE POLICY "Users can create their own meal plans"
    ON meal_plan FOR INSERT
    WITH CHECK (auth.uid() = author_id);

-- Policy: Users can update their own meal plans
CREATE POLICY "Users can update their own meal plans"
    ON meal_plan FOR UPDATE
    USING (auth.uid() = author_id);

-- Policy: Users can delete their own meal plans
CREATE POLICY "Users can delete their own meal plans"
    ON meal_plan FOR DELETE
    USING (auth.uid() = author_id);


CREATE TABLE IF NOT EXISTS meal_plan_day (
    id BIGINT not null generated by default as identity primary key,
    day TEXT NOT NULL,
    total_calories INTEGER NOT NULL CHECK (total_calories >= 0),
    meal_plan_id BIGINT NOT NULL REFERENCES meal_plan(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS for meal_plan_day
ALTER TABLE meal_plan_day ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view days
CREATE POLICY "Days are viewable by everyone"
    ON meal_plan_day FOR SELECT
    USING (true);

-- Policy: Users can insert days into their own meal plans
CREATE POLICY "Users can insert days into their own meal plans"
    ON meal_plan_day FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM meal_plan 
            WHERE meal_plan.id = meal_plan_day.meal_plan_id 
            AND meal_plan.author_id = auth.uid()
        )
    );

-- Policy: Users can update days in their own meal plans
CREATE POLICY "Users can update their own days"
    ON meal_plan_day FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM meal_plan 
            WHERE meal_plan.id = meal_plan_day.meal_plan_id 
            AND meal_plan.author_id = auth.uid()
        )
    );

-- Policy: Users can delete days from their own meal plans
CREATE POLICY "Users can delete their own days"
    ON meal_plan_day FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM meal_plan 
            WHERE meal_plan.id = meal_plan_day.meal_plan_id 
            AND meal_plan.author_id = auth.uid()
        )
    );


CREATE TABLE IF NOT EXISTS meal_plan_meal (
    id BIGINT not null generated by default as identity primary key,
    name TEXT NOT NULL,
    description TEXT,
    calories INTEGER CHECK (calories >= 0),
    protein INTEGER CHECK (protein >= 0),
    carbs INTEGER CHECK (carbs >= 0),
    fat INTEGER CHECK (fat >= 0),
    day_id BIGINT NOT NULL REFERENCES meal_plan_day(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS for meal_plan_meal
ALTER TABLE meal_plan_meal ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view meals
CREATE POLICY "Meals are viewable by everyone"
    ON meal_plan_meal FOR SELECT
    USING (true);

-- Policy: Users can insert meals into their own meal plans
CREATE POLICY "Users can insert meals into their own meal plans"
    ON meal_plan_meal FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 
            FROM meal_plan_day 
            JOIN meal_plan ON meal_plan.id = meal_plan_day.meal_plan_id
            WHERE meal_plan_day.id = meal_plan_meal.day_id 
            AND meal_plan.author_id = auth.uid()
        )
    );

-- Policy: Users can update meals in their own meal plans
CREATE POLICY "Users can update their own meals"
    ON meal_plan_meal FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 
            FROM meal_plan_day 
            JOIN meal_plan ON meal_plan.id = meal_plan_day.meal_plan_id
            WHERE meal_plan_day.id = meal_plan_meal.day_id 
            AND meal_plan.author_id = auth.uid()
        )
    );

-- Policy: Users can delete meals from their own meal plans
CREATE POLICY "Users can delete their own meals"
    ON meal_plan_meal FOR DELETE
    USING (
        EXISTS (
            SELECT 1 
            FROM meal_plan_day 
            JOIN meal_plan ON meal_plan.id = meal_plan_day.meal_plan_id
            WHERE meal_plan_day.id = meal_plan_meal.day_id 
            AND meal_plan.author_id = auth.uid()
        )
    );