CREATE TABLE profile_image (
    id BIGINT generated by default  as identity primary key,
    url TEXT not null,
    path TEXT not null,
    profile_id uuid not null references profile(id) on  delete cascade
)


-- ENABLE RLS
ALTER TABLE profile_image ENABLE ROW LEVEL SECURITY


-- users can view thier own image
create policy "Users can view their own profile image"
on profile_image
for select
using (auth.uid() = profile_id);


-- user can insert profile image
create policy "Users can insert their own profile image"
on profile_image
for insert
with check (auth.uid() = profile_id);

-- user can update thier own  profile picture
create policy "Users can update their own profile image"
on profile_image
for update
using (auth.uid() = profile_id);

-- allow profile to delete profile picture
create policy "Users can delete their own profile image"
on profile_image
for delete
using (auth.uid() = profile_id);
