CREATE TABLE IF NOT EXISTS profile_image (
    id BIGINT generated by default as identity primary key,
    url TEXT not null,
    path TEXT not null,
    profile_id uuid not null references profile(id) on delete cascade
);

CREATE INDEX IF NOT EXISTS idx_profile_image_profile_id ON profile_image(profile_id);

-- ENABLE RLS
ALTER TABLE profile_image ENABLE ROW LEVEL SECURITY;

-- Anyone can view profile images so authors/commenters are visible across the site
DROP POLICY IF EXISTS "Users can view their own profile image" ON profile_image;
DROP POLICY IF EXISTS "Anyone can view profile images" ON profile_image;
CREATE POLICY "Anyone can view profile images"
ON profile_image FOR SELECT
USING (true);

-- User can insert their own profile image
DROP POLICY IF EXISTS "Users can insert their own profile image" ON profile_image;
CREATE POLICY "Users can insert their own profile image"
ON profile_image FOR INSERT
WITH CHECK (auth.uid() = profile_id);

-- User can update their own profile image
DROP POLICY IF EXISTS "Users can update their own profile image" ON profile_image;
CREATE POLICY "Users can update their own profile image"
ON profile_image FOR UPDATE
USING (auth.uid() = profile_id);

-- User can delete their own profile image
DROP POLICY IF EXISTS "Users can delete their own profile image" ON profile_image;
CREATE POLICY "Users can delete their own profile image"
ON profile_image FOR DELETE
USING (auth.uid() = profile_id);
