-- ============================================
-- RESTAURANT TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS restaurant (
    id BIGINT generated by default  as identity primary key,
    name TEXT NOT NULL,
    description,
    cuisine,
    address,
    phone,
    email,
    website,
    google_map_url,
    image JSONB,
    menu JSONB,
    gallery JSONB,
    rating DECIMAL(2,1) DEFAULT 0,
    author_id UUID NOT NULL REFERENCES profile(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT rating_range CHECK (rating >= 0 AND rating <= 5)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_restaurant_author_id ON restaurant(author_id);
CREATE INDEX IF NOT EXISTS idx_restaurant_cuisine ON restaurant(cuisine);
CREATE INDEX IF NOT EXISTS idx_restaurant_created_at ON restaurant(created_at DESC);

-- Auto-update updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_restaurant_updated_at
    BEFORE UPDATE ON restaurant
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Row Level Security
ALTER TABLE restaurant ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Restaurants are viewable by everyone"
    ON restaurant FOR SELECT
    USING (true);

CREATE POLICY "Users can create their own restaurants"
    ON restaurant FOR INSERT
    WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update their own restaurants"
    ON restaurant FOR UPDATE
    USING (auth.uid() = author_id);

CREATE POLICY "Users can delete their own restaurants"
    ON restaurant FOR DELETE
    USING (auth.uid() = author_id);

-- ============================================
-- RESTAURANT REVIEWS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS restaurant_review (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    restaurant_id UUID NOT NULL REFERENCES restaurant(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES profile(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT NOT NULL CHECK (char_length(comment) >= 10 AND char_length(comment) <= 500),
    name TEXT NOT NULL CHECK (char_length(name) >= 2 AND char_length(name) <= 100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE(restaurant_id, author_id)
);

CREATE INDEX IF NOT EXISTS idx_restaurant_review_restaurant_id ON restaurant_review(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_restaurant_review_author_id ON restaurant_review(author_id);

CREATE TRIGGER update_restaurant_review_updated_at
    BEFORE UPDATE ON restaurant_review
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- RLS for reviews
ALTER TABLE restaurant_review ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone"
    ON restaurant_review FOR SELECT
    USING (true);

CREATE POLICY "Users can create reviews"
    ON restaurant_review FOR INSERT
    WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update their own reviews"
    ON restaurant_review FOR UPDATE
    USING (auth.uid() = author_id);

CREATE POLICY "Users can delete their own reviews"
    ON restaurant_review FOR DELETE
    USING (auth.uid() = author_id);